import React from 'react'

import { ReactComponent as ReactLogo } from '../img/logo-react.svg'
import { ReactComponent as ReduxLogo } from '../img/logo-redux.svg'
import { ReactComponent as JSLogo } from '../img/logo-javascript.svg'
import { ReactComponent as CssLogo } from '../img/logo-css.svg'
import { ReactComponent as FirebaseLogo } from '../img/logo-firebase.svg'
import { ReactComponent as GitLogo } from '../img/logo-git.svg'
import { ReactComponent as HtmlLogo } from '../img/logo-html.svg'
import { ReactComponent as JQueryLogo } from '../img/logo-jquery.svg'
import { ReactComponent as NodeLogo } from '../img/logo-node.svg'
import { ReactComponent as VscodeLogo } from '../img/logo-vscode.svg'
import { ReactComponent as MaterialuiLogo } from '../img/logo-material-ui.svg'

export const logoComponents = [
  <ReactLogo />,
  <ReduxLogo />,
  <JSLogo />,
  <CssLogo />,
  <FirebaseLogo />,
  <GitLogo />,
  <HtmlLogo />,
  <JQueryLogo />,
  <NodeLogo />,
  <VscodeLogo />,
  <MaterialuiLogo />,
]

export function displayLogo(index) {
  const logos = [
    <ReactLogo />,
    <ReduxLogo />,
    <JSLogo />,
    <CssLogo />,
    <FirebaseLogo />,
    <GitLogo />,
    <HtmlLogo />,
    <JQueryLogo />,
    <NodeLogo />,
    <VscodeLogo />,
    <MaterialuiLogo />,
  ]
  return logos[index]
}

export const svgAndName = [
  {svg: <ReactLogo />, name: 'react'},
  {svg: <ReduxLogo />, name: 'redux'},
  {svg: <JSLogo />, name: 'javascript'},
  {svg: <CssLogo />, name: 'css3'},
  {svg: <FirebaseLogo />, name: 'firebase'},
  {svg: <GitLogo />, name: 'git'},
  {svg: <HtmlLogo />, name: 'html5'},
  {svg: <JQueryLogo />, name: 'jQuery'},
  {svg: <NodeLogo />, name: 'node'},
  {svg: <VscodeLogo />, name: 'vs code'},
  {svg: <MaterialuiLogo />, name: 'material-ui'},
]

export const arrRandNums = [
  8,
  5,
  0,
  9,
  2,
  7,
  5,
  10,
  3,
  4,
  3,
  1,
  4,
  10,
  4,
  2,
  3,
  7,
  10,
  5,
  7,
  9,
  0,
  7,
  8,
  2,
  9,
  2,
  0,
  4,
  1,
  5,
  9,
  6,
  7,
  5,
  6,
  8,
  0,
  3,
  6,
  1,
  9,
  5,
  5,
  4,
  0,
  3,
  3,
  2,
  10,
  9,
  7,
  2,
  10,
  8,
  3,
  0,
  8,
  4,
  5,
  2,
  1,
  2,
  3,
  10,
  6,
  7,
  2,
  10,
  1,
  4,
  1,
  0,
  8,
  6,
  0,
  10,
  3,
  1,
  5,
  4,
  2,
  2,
  10,
  8,
  0,
  6,
  7,
  4,
  10,
  6,
  4,
  2,
  3,
  4,
  8,
  1,
  9
]
